name: GitHub 3D Contribution Graph
on:
  schedule:
  - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Main Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAX_REPOS: 200
        USERNAME: ${{ github.repository_owner }}
    - name: Generate
      uses: yoshi389111/github-profile-3d-contrib@0.5.0
    - name: Commit & Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A .
        git commit -m "Update 3D Graph"
        git push
